### ISSUE TITLE
[Question] Why my first request still took so long to get response after setting eager load?

### ISSUE THREAD

**Issue by WilliamChen-luckbob** [Netflix/zuul#1027]
I'm using eureka and zull as client discovery and gateway.

But while testing applications, I found that the first request will take a very long time to get response.

I have read springcloud documentation and also checked for stackoverflow to find any solution.

But so far the solutions from google which I found did not solve the problem.

below is part of the configuration:

```
zuul:
  ignored-headers:
    - Vary
    - Access-Control-Allow-Origin
  ribbon:
    eager-load:
      enabled: true
  routes:
    resourceCenter:
      path: /web-resource-center/**
      serviceId: web-resource-center
      stripPrefix: true
    messageCenter:
      path: /web-message-center/**
      serviceId: web-message-center
      stripPrefix: true
    webSystem:
      path: /web-system/**
      serviceId: web-system
      stripPrefix: true
    security:
      path: /web-security/**
      serviceId: web-security
      stripPrefix: true
    taskCenter:
      path: /web-task-center/**
      serviceId: web-task-center
      stripPrefix: true
ribbon:
  eager-load:
    enabled: true
    clients:
      - web-resource-center
      - web-task-center
      - web-security
      - web-message-center
      - web-system
```
  
while not configured, the request will take 2s-4s to get response.

I have configured ribbon and zuul to eager load ,and that may speed up the first request for about 50%

while , the requests after the first one will take only less than 100ms each, I don't know why.

Also one thing here to cunfuse me : If I set a feign request in a controller then request this controller the slow response will not happen. So, are there any mistakes I have made configuring my application.yml?

please help me please,thanks a lot!
