### ISSUE TITLE
Multiple routes are configured incorrectly

### ISSUE THREAD

**Issue by zhipeng0703** [Netflix/zuul#1869]
# The version of zuul used is spring-cloud-starter-netflix-zuul-2.2.5
# Multiple routes are configured incorrectly，The first route /student and the second route /teacher are normal on the first visit, and the second visit reports an error of 404 on the first route /student and everything is normal on the second route /teacher
# this is my application.yml
```
zuul:
  ignored-services: "*"
  routes:
    micro-student: /student/**
    micro-teacher: /teacher/**
```
![image](https://github.com/user-attachments/assets/0289f617-0ece-43df-af8a-cc987661ea3a)
