### ISSUE TITLE
Question: Is it possible to access Zuul routes programmatically to retrieve service ID?

### ISSUE THREAD

**Issue by KeiichiTheOtaku** [Netflix/zuul#229]
I'm working on a ZuulFilter with functionality to override route host based on service ID when an override is set on a header token, but in order to do so I need to identify the service ID associated with the URL.

Say I have the following route in my zuul.yml file:

```
    example-service:
      path: /example/**
      serviceId: exampleservice
      stripPrefix: true
```

From the RequestContext, I can get the URL path; what I need to retrieve from the route is the serviceId associated with that path, to match to my override key, so that I can set the route host.

Is it possible to get the serviceId value on the route configuration, programmatically, at runtime?
