### ISSUE TITLE
Is it possible to Create route for Local file system ?? 

### ISSUE THREAD

**Issue by vasandharaj** [Netflix/zuul#336]
Is it possible to create route for the local file system in Zuul?? 

please find the sample configuration 

```
zuul:
    routes:
       files:
           path: /files/**
            serviceId: files
            url: file:D:\tmp1\
```
