### ISSUE TITLE
Zuul Eureka Service Id redirection

### ISSUE THREAD

**Issue by Tanmayghosh** [Netflix/zuul#366]
I am having few spring boot microservices, which are deployed to JBoss over a cloud environment. These boot services are Eureka clients which register itself in to the Eureka server. Following is an example: 
eureka:
```

  client:
    healthcheck:
        enabled: true
    serviceUrl:
       defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/

     
  instance:
    ip-address: 127.0.0.1
    appname: user-regn-service-app
    home-page-url-path: /user-regn-service-app
```

It registers the app with Eureka with the name user-regn-service-app
![image](https://user-images.githubusercontent.com/8774991/31230790-b3440b6c-aa02-11e7-9819-a33094cedd27.png)

The weblogic server is running at 8080 and the user-regn-service-app is deployed at the context path _/user-regn-service-app._
So the rest api is as below
`localhost:8080/user-regn-service-app/regnUser`

When I am using zuul as api gateway, the config is as below

```

zuul:
  prefix: /api
  routes:
    test:
      path: /test/**
      service-id: USER-REGN-SERVICE-APP
      strip-prefix: true
       

ribbon:
  eureka:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: false
```

But whenever I am making call to zuul api gateway it is unable to recognize the context path and redirects to localhost:8080 instead of localhost:8080/user-regn-service-app.

http://localhost:8765/api/ -> 404 not found
http://localhost:8765/api/user-regn-service-app/ -> Wildfly default homepage
 
![image](https://user-images.githubusercontent.com/8774991/31230822-c4a719d0-aa02-11e7-8cf0-61b1e0493acd.png)

http://localhost:8765/api/user-regn-service-app/user-regn-service-app/regnUser -> Redirects to user registration.
Expected behavior: http://localhost:8765/api/test/regnUser should redirect to the user registration.

 I have pretty much tried all combinations that I got from blogs between Zuul and Eureka to get the following done but no luck. Kindly advise if I am missing something.
