### ISSUE TITLE
Full path rewrites when defining routes

### ISSUE THREAD

**Issue by wederbrand** [Netflix/zuul#374]
IMHO the current way of doing routing, with services ids and path-prefixes exposes too much of the internal domain.

If I do 
```
zuul:
  routes:
    foobar:
      path: /foo/**
      url: http://fooBarServce:8181/
```
The url **/foo/1234/bar/5678** would be proxied to **http://fooBarService:8181/1234/bar/5678**, forcing my external callers to use the exact same paths as my internal service, at least after **/foo/**.

IMO it should be possible to totally rewrite the path to the internal services, and by doing so building a new external api, completely hiding the internal ones.  

Something like this.
```
zuul:
  routes:
    foobar:
      path: /foo/(.*)/bar/(.*)
      url: http://fooBarServce:8181/$2/$1
```
would translate **/foo/1234/bar/5678** into **http://fooBarService:8181/5678/1234**

If this is already possible through some cunning pre- , routing and post-filters I've failed to find out how and would be glad for some pointers.
