### ISSUE TITLE
zuul route response 307 http code 

### ISSUE THREAD

**Issue by ileler** [Netflix/zuul#449]
i configuration in my bootstrap.yml
```
zuul:
  routes:
    backendApi:
       path: /api/fmbe/**
       stripPrefix: true
       url: http://172.16.2.136:9091/api/fmbe
```

and request from frontend,get 307 http code.
