### ISSUE TITLE
more than 1 matching path causing request forwarding causing issues

### ISSUE THREAD

**Issue by userAshish** [Netflix/zuul#521]
```
 cxp-customerAuthenticateMethods-Path:
      path: //customer/authentication
      serviceId: my-service-1
      stripPrefix: false
 cxp-customer-path:
      path: /customer/**
      stripPrefix: false
      url: myotherservces.com
```

for my request http://api-gateway-host.com**/customer/authentication, I  expected this request to be forwarded to first matching entry  but its getting forwarded to customer/**  (i.e 2nd match) what I can do to fix this issue 

Note: first math is having a Eureka registered service ID and 2nd match customer/** is forwarding it to url
