### ISSUE TITLE
High CPU usage with zuul 

### ISSUE THREAD

**Issue by mahamafzar** [Netflix/zuul#661]
I using zuul as ingress on my microservice infrastructure, I have more than 5K users, zuul using more than %600 CPU, What is wrong?

 ```
ribbon: #LoadBalancer
  ReadTimeout: 20000
  ConnectTimeout: 20000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000
zuul: #Gatway Proxy
  ignore-security-headers: false
  ignored-headers: X-Content-Type-Options,Strict-Transport-Security,X-Frame-Options,X-XSS-Protection
  semaphore:
    max-semaphores: 10000

  set-content-length: true
  ignoredServices: '*'
  #prefix: /api
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000
  routes:
    app-service:
      path: /app/**
      serviceId: app-service
      stripPrefix: false
      sensitiveHeaders:
```
