### ISSUE TITLE
How to proxy to https instead http?

### ISSUE THREAD

**Issue by SMakhrov** [Netflix/zuul#964]
Hi!

Could help anyone? How to configure Zuul2 to proxy to https addr? By default all proxied to http.

I can't configure Zuul2 as reverse-proxy for requests to https address (for example https://someurl.com).

I have tried to specify in application.properties the following:
```
api.ribbon.listOfServers=someurl.com:443
api.ribbon.client.NIWSServerListClassName=com.netflix.loadbalancer.ConfigurationBasedServerList
```
And in HttpInboundSyncFilter have done this:
```
request.getHeaders().set("Host", "https://someurl.com")
request.setRouteVIP("api")
request.setScheme("https");
request.setPort(443);
```
But I've got 502 Bad gateway error.

Could you tell me please what do I need for proxying requests to url with https?

**Comment by SMakhrov** [comment]
@carl-mastrangelo, @artgon ?

**Comment by vembry** [comment]
I think you can define directly on the `ribbon.listOfServers` props. 
```
api.ribbon.listOfServers=https://someurl.com:443
api.ribbon.client.NIWSServerListClassName=com.netflix.loadbalancer.ConfigurationBasedServerList
```
____
we personally used it like that in our zuul gateway(we are using yml)
```
profile:
  ribbon:
    listOfServers: https://some-random-url.com:443/
    ConnectTimeout: 2000
    ReadTimeout: 5000
    MaxTotalHttpConnections: 100
    MaxConnectionsPerHost: 100
```

which essentially in props
```
profile.ribbon.listOfServers=https://some-random-url.com:443/
profile.ribbon.client.ConnectTimeout=2000
profile.ribbon.ReadTimeout=5000
profile.ribbon.MaxTotalHttpConnections=100
profile.ribbon.MaxConnectionsPerHost=100
```
